---
- name: Install Dependency packages
  package:
    name:
      - acl
      - sudo
      - python3-pexpect
    state: present
  register: apt_status
  until: apt_status is success
  delay: 6
  retries: 10

- name: Create temporary build directory for Guac
  ansible.builtin.tempfile:
    state: directory
  register: my_app_temp_dir_raw

- name: Play Temporary Path
  ansible.builtin.set_fact:
    my_app_temp_dir: "{{ my_app_temp_dir_raw.path }}"
